services:

  surveyor:
    volumes:
      # use this for development, and debugging if needed
      - $PWD/surveyor/webapp:/opt/app/surveyor

  surveyor_worker:
    volumes:
      # use this for development, and debugging if needed
      - $PWD/surveyor/webapp:/opt/app/surveyor

