name: Deploy Surveyor to VM

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Surveyor Environment to Deploy'
        type: environment
        required: true
      action:
        description: 'Action to Perform'
        type: choice
        options:
          - 'test'
          - 'deploy'
          - 'revert'

run-name: ${{ github.event.inputs.environment }} - Surveyor Deployment Action ${{ github.event.inputs.action }}

jobs:

  deploy-surveyor:

    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      ENV_NAME: ${{ github.event.inputs.environment }}
      # INFRA_NAME: ${{ vars.INFRA_NAME }}

    steps:

      # - name: SSH to remote host
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ vars.DEPLOY_HOST }}
      #     username: ${{ vars.DEPLOY_USER }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull latest surveyor code
        run: ssh ${{ vars.DEPLOY_USER }}@${{ vars.DEPLOY_HOST }} 'cd /opt/docker/surveyor && git pull'

      - name: Stop Existing Surveyor Docker Containers
        run: ssh ${{ vars.DEPLOY_USER }}@${{ vars.DEPLOY_HOST }} 'cd /opt/docker/surveyor && docker compose down'

      - name: Build and Start new Surveyor Docker Containers
        run: ssh ${{ vars.DEPLOY_USER }}@${{ vars.DEPLOY_HOST }} 'cd /opt/docker/surveyor && docker compose up --build -d'

      - name: Restart NGINX Webhost
        run: ssh ${{ vars.DEPLOY_USER }}@${{ vars.DEPLOY_HOST }} 'cd /opt/docker/webhost && docker compose restart'
