# Generated by Django 4.2.8 on 2024-01-16 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyorOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InfluxSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('host', models.CharField(max_length=60, null=True)),
                ('path', models.CharField(max_length=30, null=True)),
                ('dbname', models.CharField(max_length=30, null=True)),
                ('influx_org', models.CharField(blank=True, default='', max_length=30)),
                ('influx_token', models.CharField(blank=True, default='', max_length=100)),
                ('surveyor_org', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='device.surveyororg')),
            ],
        ),
        migrations.CreateModel(
            name='EndNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, unique=True)),
                ('dev_eui', models.CharField(default='', max_length=16)),
                ('influx_measurement', models.CharField(default='nameofmeas', max_length=30, null=True)),
                ('app_eui', models.CharField(blank=True, default='', max_length=20)),
                ('app_key', models.CharField(blank=True, default='', max_length=40)),
                ('frequency_plan', models.CharField(blank=True, default='', max_length=20)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=40)),
                ('model', models.CharField(blank=True, default='', max_length=40)),
                ('revision', models.CharField(blank=True, default='', max_length=10)),
                ('gps_payload', models.BooleanField(default=False)),
                ('influx_source', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='device.influxsource')),
                ('surveyor_org', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='device.surveyororg')),
            ],
            options={
                'ordering': ('surveyor_org', 'name'),
            },
        ),
        migrations.CreateModel(
            name='BucketDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_eui', models.CharField(max_length=16)),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('marker', models.CharField(blank=True, default='', max_length=30)),
                ('address', models.CharField(blank=True, default='', max_length=50)),
                ('influx_source', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='device.influxsource')),
            ],
            options={
                'ordering': ('influx_source', 'name'),
            },
        ),
    ]
