# Generated by Django 5.0.4 on 2024-04-16 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyororg',
            options={'ordering': ('name',)},
        ),
    ]
