# Generated by Django 5.0.4 on 2024-06-07 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_channelplan_influxsource_channel_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influxsource',
            name='channel_plan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.channelplan'),
        ),
    ]
