# Generated by Django 5.0.6 on 2024-06-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_alter_influxsource_channel_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='endnode',
            name='downlinks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='endnode',
            name='influx_measurement_downlinks',
            field=models.CharField(default='nameofdownmeas', max_length=30, null=True),
        ),
    ]
