# Generated by Django 5.0.6 on 2024-07-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_endnode_downlinks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketdevice',
            name='report_group',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
