# Generated by Django 5.0.6 on 2024-08-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_bucketdevice_report_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='influxsource',
            name='influx_v3',
            field=models.BooleanField(default=False),
        ),
    ]
