# Generated by Django 5.1 on 2024-09-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_influxsource_influx_v3'),
    ]

    operations = [
        migrations.AddField(
            model_name='influxsource',
            name='downlinks',
            field=models.BooleanField(default=False),
        ),
    ]
