# Generated by Django 5.1 on 2024-09-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_influxsource_downlinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='influxsource',
            name='influx_measurement_downlinks',
            field=models.CharField(default='nameofdownmeas', max_length=30, null=True),
        ),
    ]
